/*
 * DXCC entity lookup.
 *
 * Both cluster feeds carry an ADIF DXCC entity code on every spot. HamQTH also
 * sends a country name and continent; DXWatch sends only the number. Resolving
 * the number here means a spot is classified the same way whichever service it
 * came from, and the most-wanted test is an exact code match rather than a
 * substring search against a name that each service spells differently.
 *
 * GENERATED by tools/gen_dxcc.py from AD1C's cty.csv - do not edit by hand.
 * Re-run it after a DXpedition changes what is most wanted, or when an entity
 * is added or deleted.
 */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define DXCC_COUNT 340
#define DXCC_MOST_WANTED_COUNT 60
#define DXCC_PREFIX_COUNT 8308
#define DXCC_PREFIX_MAX 11

typedef struct {
    uint16_t code;        /* ADIF DXCC entity code */
    uint16_t name_offset; /* into the name blob */
    char     continent[3];
} dxcc_entity_t;

typedef struct {
    char     prefix[DXCC_PREFIX_MAX + 1];
    uint16_t code;
} dxcc_prefix_t;

extern const dxcc_entity_t DXCC_TABLE[DXCC_COUNT];
extern const uint16_t DXCC_MOST_WANTED[DXCC_MOST_WANTED_COUNT];
extern const dxcc_prefix_t DXCC_PREFIXES[DXCC_PREFIX_COUNT];

/**
 * @brief Entity code for a callsign, or 0 if it cannot be placed.
 *
 * Handles compound calls: an added prefix wins over the home call, portable and
 * district markers are ignored, and maritime or aeronautical mobile resolves to
 * nothing because neither belongs to an entity.
 */
int dxcc_from_callsign(const char *call);

/** @brief Entity name, or NULL if the code is unknown. */
const char *dxcc_name(int code);

/** @brief Two-letter continent, or NULL if the code is unknown. */
const char *dxcc_continent(int code);

/** @brief True if the entity is on the most-wanted list. */
bool dxcc_is_most_wanted(int code);
