/*
 * 1-bit land/sea mask of the world, equirectangular.
 *
 * Both map projections sample this: the equirectangular view directly, the
 * azimuthal view by inverse-projecting each screen pixel to a latitude and
 * longitude first. That means no per-QTH bitmap and no polygon filling.
 *
 * GENERATED by tools/gen_landmask.py - do not edit by hand.
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#define LANDMASK_W     1024
#define LANDMASK_H     512
#define LANDMASK_BYTES (LANDMASK_W * LANDMASK_H / 8)

extern const uint8_t LANDMASK[LANDMASK_BYTES];

/** @brief True if the given position is land. Wraps in longitude, clamps in latitude. */
static inline bool landmask_at(float lat, float lon)
{
    int x = (int)((lon + 180.0f) / 360.0f * LANDMASK_W);
    int y = (int)((90.0f - lat) / 180.0f * LANDMASK_H);
    x %= LANDMASK_W;
    if (x < 0) {
        x += LANDMASK_W;
    }
    if (y < 0) {
        y = 0;
    }
    if (y >= LANDMASK_H) {
        y = LANDMASK_H - 1;
    }
    return (LANDMASK[y * (LANDMASK_W / 8) + (x >> 3)] >> (7 - (x & 7))) & 1;
}
