#!/usr/bin/env python3
"""Generate main/lib/coastline.{c,h} from Natural Earth 110m land data.

Downloads ne_110m_land.geojson (public domain), drops islands below an area
threshold, reduces each ring with Douglas-Peucker, and emits (lat, lon) rings as
C arrays. The result is small enough to live in flash, which is why the
propagation map needs no SD card.

    python tools/gen_coastline.py
"""
import json
import math
import os
import urllib.request

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
MIN_AREA = 6.0      # square degrees; drops small islands
TOLERANCE = 0.9     # degrees; Douglas-Peucker

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "main", "lib")


def ring_area(ring):
    a = 0.0
    for i in range(len(ring) - 1):
        a += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1]
    return abs(a) / 2


def simplify(pts, tol):
    if len(pts) < 3:
        return pts

    def dist(p, a, b):
        if a == b:
            return math.hypot(p[0] - a[0], p[1] - a[1])
        t = ((p[0] - a[0]) * (b[0] - a[0]) + (p[1] - a[1]) * (b[1] - a[1])) \
            / ((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2)
        t = max(0.0, min(1.0, t))
        px, py = a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1])
        return math.hypot(p[0] - px, p[1] - py)

    dmax, idx = 0.0, 0
    for i in range(1, len(pts) - 1):
        d = dist(pts[i], pts[0], pts[-1])
        if d > dmax:
            dmax, idx = d, i
    if dmax > tol:
        return simplify(pts[:idx + 1], tol)[:-1] + simplify(pts[idx:], tol)
    return [pts[0], pts[-1]]


def cfloat(v):
    """C float literal. %g alone yields '37', and '37f' is not valid C."""
    s = "%g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def main():
    raw = json.load(urllib.request.urlopen(URL, timeout=60))

    polys = []
    for feature in raw["features"]:
        geom = feature["geometry"]
        if geom["type"] == "Polygon":
            rings = [geom["coordinates"][0]]
        else:
            rings = [part[0] for part in geom["coordinates"]]
        for ring in rings:
            if ring_area(ring) < MIN_AREA:
                continue
            simp = simplify([tuple(p) for p in ring], TOLERANCE)
            if len(simp) >= 4:
                polys.append([(round(lat, 2), round(lon, 2)) for lon, lat in simp])

    polys.sort(key=len, reverse=True)
    total = sum(len(p) for p in polys)
    longest = max(len(p) for p in polys)

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "coastline.c"), "w", encoding="utf-8") as f:
        f.write("/*\n * Simplified Natural Earth 110m land outline (public domain).\n"
                " *\n * GENERATED by tools/gen_coastline.py - do not edit by hand.\n */\n"
                '#include "lib/coastline.h"\n\n')
        for i, p in enumerate(polys):
            f.write("static const coastline_pt_t p%d[] = {" % i)
            f.write(",".join("{%s,%s}" % (cfloat(a), cfloat(b)) for a, b in p))
            f.write("};\n")
        f.write("\nconst coastline_poly_t COASTLINE[COASTLINE_COUNT] = {\n")
        for i, p in enumerate(polys):
            f.write("    {p%d, %d},\n" % (i, len(p)))
        f.write("};\n")

    with open(os.path.join(OUT, "coastline.h"), "w", encoding="utf-8") as f:
        f.write("""/*
 * Simplified world coastline, as (lat, lon) rings.
 *
 * %d landmasses, %d points. Enough to make a propagation map legible without
 * needing map tiles on an SD card.
 *
 * GENERATED by tools/gen_coastline.py - do not edit by hand.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define COASTLINE_COUNT      %d
#define COASTLINE_MAX_POINTS %d

typedef struct {
    float lat;
    float lon;
} coastline_pt_t;

typedef struct {
    const coastline_pt_t *pts;
    int count;
} coastline_poly_t;

extern const coastline_poly_t COASTLINE[COASTLINE_COUNT];

#ifdef __cplusplus
}
#endif
""" % (len(polys), total, len(polys), longest))

    print("wrote %d polygons, %d points, longest ring %d" % (len(polys), total, longest))


if __name__ == "__main__":
    main()
