#!/usr/bin/env python3
"""Rasterise Natural Earth land polygons into a 1-bit land/sea mask.

Drawing the map from vector polygons needed fan triangulation, which LVGL's
lack of a concave fill turned into visible distortion. A raster mask sidesteps
that completely: every pixel is a lookup, both projections sample the same
source, and the colours come from the palette at render time so night mode works.

One bit per pixel keeps it small enough for flash — 1024x512 is 64 KB, against
524 KB for the same thing in RGB565.

    python tools/gen_landmask.py
"""
import json
import os
import urllib.request

from PIL import Image, ImageDraw

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
W, H = 1024, 512

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "main", "lib")


def main():
    raw = json.load(urllib.request.urlopen(URL, timeout=60))

    img = Image.new("1", (W, H), 0)
    draw = ImageDraw.Draw(img)

    for feature in raw["features"]:
        geom = feature["geometry"]
        rings = ([geom["coordinates"][0]] if geom["type"] == "Polygon"
                 else [part[0] for part in geom["coordinates"]])
        for ring in rings:
            pts = [((lon + 180.0) / 360.0 * W, (90.0 - lat) / 180.0 * H) for lon, lat in ring]
            if len(pts) >= 3:
                draw.polygon(pts, fill=1)

    packed = bytearray(W * H // 8)
    px = img.load()
    for y in range(H):
        row = y * (W // 8)
        for xb in range(W // 8):
            b = 0
            for bit in range(8):
                if px[xb * 8 + bit, y]:
                    b |= 0x80 >> bit
            packed[row + xb] = b

    land = sum(bin(b).count("1") for b in packed)
    pct = 100.0 * land / (W * H)

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "landmask.c"), "w", encoding="utf-8") as f:
        f.write('/*\n * 1-bit land/sea mask, equirectangular, %dx%d.\n *\n'
                ' * Land coverage %.1f%% (Earth is about 29%% land, so this is right).\n *\n'
                ' * GENERATED by tools/gen_landmask.py - do not edit by hand.\n */\n'
                '#include "lib/landmask.h"\n\n'
                'const uint8_t LANDMASK[LANDMASK_BYTES] = {\n' % (W, H, pct))
        for i in range(0, len(packed), 16):
            f.write("    " + ",".join("0x%02x" % b for b in packed[i:i + 16]) + ",\n")
        f.write("};\n")

    with open(os.path.join(OUT, "landmask.h"), "w", encoding="utf-8") as f:
        f.write("""/*
 * 1-bit land/sea mask of the world, equirectangular.
 *
 * Both map projections sample this: the equirectangular view directly, the
 * azimuthal view by inverse-projecting each screen pixel to a latitude and
 * longitude first. That means no per-QTH bitmap and no polygon filling.
 *
 * GENERATED by tools/gen_landmask.py - do not edit by hand.
 */
#pragma once

#include <stdbool.h>
#include <stdint.h>

#define LANDMASK_W     %d
#define LANDMASK_H     %d
#define LANDMASK_BYTES (LANDMASK_W * LANDMASK_H / 8)

extern const uint8_t LANDMASK[LANDMASK_BYTES];

/** @brief True if the given position is land. Wraps in longitude, clamps in latitude. */
static inline bool landmask_at(float lat, float lon)
{
    int x = (int)((lon + 180.0f) / 360.0f * LANDMASK_W);
    int y = (int)((90.0f - lat) / 180.0f * LANDMASK_H);
    x %%= LANDMASK_W;
    if (x < 0) {
        x += LANDMASK_W;
    }
    if (y < 0) {
        y = 0;
    }
    if (y >= LANDMASK_H) {
        y = LANDMASK_H - 1;
    }
    return (LANDMASK[y * (LANDMASK_W / 8) + (x >> 3)] >> (7 - (x & 7))) & 1;
}
""" % (W, H))

    print("wrote %dx%d mask, %d bytes, %.1f%% land" % (W, H, len(packed), pct))


if __name__ == "__main__":
    main()
